import Image from 'next/image'
import { Inter } from 'next/font/google'
import Head from 'next/head'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import Layout from '@/components/Layout'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Extenders Charity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.jpeg" />
      </Head>
      <main className='mt-32'>
        
        <h1>Hey I am home page</h1>
        
      </main>
    </div>
  )
}
