import { Inter } from 'next/font/google'
import Head from 'next/head'
import MidsectionHome from '@/components/MidsectionHome'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Extenders Charity</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/logo.jpeg" />
      </Head>
      <main className='mt-32'>
    
<MidsectionHome />

</main>
</div>
  )
}
